// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0v-WnT07zTUtSef-RTKvi__Sx2Jj0G-o',
    appId: '1:13869856204:web:2eeb4846e9f81077a81969',
    messagingSenderId: '13869856204',
    projectId: 'authtutorial-e9e04',
    authDomain: 'authtutorial-e9e04.firebaseapp.com',
    storageBucket: 'authtutorial-e9e04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjtOQbweSzEGhfkCgJNQVWvFCVLl9u5I',
    appId: '1:13869856204:android:a3a06296ba8bac3ba81969',
    messagingSenderId: '13869856204',
    projectId: 'authtutorial-e9e04',
    storageBucket: 'authtutorial-e9e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAce3c5Otf3nFhUmoyaE-xZ2EPC2cQAHSI',
    appId: '1:13869856204:ios:e2cdec4f4ce777b0a81969',
    messagingSenderId: '13869856204',
    projectId: 'authtutorial-e9e04',
    storageBucket: 'authtutorial-e9e04.appspot.com',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAce3c5Otf3nFhUmoyaE-xZ2EPC2cQAHSI',
    appId: '1:13869856204:ios:a048f6b182ccd552a81969',
    messagingSenderId: '13869856204',
    projectId: 'authtutorial-e9e04',
    storageBucket: 'authtutorial-e9e04.appspot.com',
    iosBundleId: 'com.example.registration.RunnerTests',
  );
}
